services:
  - type: web
    name: rest-express-api
    runtime: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        fromDatabase:
          name: rest-express-db
          property: connectionString
    healthCheckPath: /api/health

  - type: web
    name: rest-express-frontend
    runtime: static
    buildCommand: npm run client:build
    staticPublishPath: ./client/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: rest-express-api
          property: host

databases:
  - name: rest-express-db
    databaseName: rest_express
    user: rest_express_user
    plan: starter
